services:
  python-test:
    image: python:3.11.13
    working_dir: /python
    volumes:
      - ./python:/python
    command: >
      sh -c "pip install -r requirements.txt && pytest tests/ -s -v"
  dotnet-test:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "dotnet test AiGeneratedApi.Tests"
