services:
  event-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__Key=this-is-a-fallback-and-it-does-not-matter
      - ConnectionStrings__DefaultConnection=Data Source=/app/Data/event_management.db
    volumes:
      - ./wwwroot:/app/wwwroot
      - sqlite_data:/app/Data
    restart: unless-stopped

volumes:
  sqlite_data: 