services:
  event-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    volumes:
      - ./wwwroot:/app/wwwroot
      - sqlite_data:/app/Data
    restart: unless-stopped

volumes:
  sqlite_data: 